#ifndef __DEFINATION_H__
#define __DEFINATION_H__

#define BITMASK_TANK 1000
#define BITMASK_RADA 1001
#define BITMASK_BOTTANK 1003
#define BITMASK_BULLET 1004
#define BITMASK_SCANNER 1005
#define PAUSE_EXCEPTION_TAG 1006 
#define BITMASK_SHOT 0
#define BITMASK_LAZER 1
#define BITMASK_BOOM 2
#define BITMASK_ITEM 4
#define TANK_BULLET_COUNT 3
#define TIME_RADA_COUNTDOWN 25

#define Z_ORDER_BACKGROUND 0
#define Z_ORDER_ITEM 1000
#define Z_ORDER_BOT 2000
#define Z_ORDER_BULLET 2000
#define Z_ORDER_TANK 3000
#define Z_ORDER_EXLODING 4000
#define Z_ORDER_SCANNER 5000
#define Z_ORDER_TOP 6000

#define PROBABILITY_COINS 35
#define TANK_SKIN_COUNT 12
#define WORLD_SCALE 0.534f
#endif 
